# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foundation_name', models.CharField(max_length=200)),
                ('foundation_description', models.TextField()),
                ('foundation_logo', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
            options={
                'db_table': 'foundation',
            },
        ),
    ]
