# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundation',
            options={'verbose_name': '\u0424\u043e\u043d\u0434', 'verbose_name_plural': '\u0424\u043e\u043d\u0434\u044b'},
        ),
    ]
