# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_percent', models.CharField(max_length=3, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u0434\u043b\u044f \u0431\u043b\u0430\u0433\u043e\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u043d\u043e\u0441\u0442\u0438')),
            ],
            options={
                'db_table': 'charity',
                'verbose_name': '\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u0431\u043b\u0430\u0433\u043e\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u043d\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u041f\u0440\u043e\u0446\u0435\u043d\u0442\u044b \u0431\u043b\u0430\u0433\u043e\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u043d\u043e\u0441\u0442\u0435\u0439',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments_text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f')),
                ('comments_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442',
                'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('item_image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('item_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_likes', models.IntegerField(default=0)),
                ('item_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'item',
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'item_category',
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u0430',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0442\u043e\u0432\u0430\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'main_category',
                'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u0413\u043b\u0430\u0432\u043d\u044b\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='item_category_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.MainCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Charity'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_foundation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.Foundation'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
    ]
