# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
