# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20160526_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=0, upload_to=b''),
        ),
    ]
