# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemCategory', verbose_name='\u0412\u044b\u0431\u0438\u0440\u0438\u0442\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Charity', verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u0434\u043b\u044f \u0431\u043b\u0430\u0433\u043e\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u043d\u043e\u0441\u0442\u0435\u0439'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_foundation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.Foundation', verbose_name='\u0412\u044b\u0431\u0438\u0440\u0438\u0442\u0435 \u0424\u043e\u043d\u0434'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_likes',
            field=models.IntegerField(default=0, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_quantity',
            field=models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='item_category_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.MainCategory', verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='item_category_name',
            field=models.CharField(max_length=50, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='main_category_name',
            field=models.CharField(max_length=50, verbose_name='\u0413\u043b\u0430\u0432\u043d\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
