# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
