# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20160527_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_charity_id',
            new_name='item_charity',
        ),
    ]
