# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20160527_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'item_category',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.ItemCategory'),
        ),
    ]
