# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20160528_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'main_category',
            },
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='item_category_main_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.MainCategory'),
        ),
    ]
