# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20160531_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_charity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Charity'),
        ),
    ]
