# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20160531_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_percent',
            field=models.SmallIntegerField(default=0),
        ),
    ]
