# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_auto_20160531_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_percent',
            field=models.CharField(max_length=3),
        ),
    ]
