# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20160531_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_percent',
            field=models.CharField(max_length=3, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u0434\u043b\u044f \u0431\u043b\u0430\u0433\u043e\u0442\u0432\u043e\u0440\u0438\u0442\u0435\u043b\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 31, 9, 43, 21, 591277, tzinfo=utc)),
        ),
    ]
