# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20160530_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('cart',), 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
