# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20160530_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('cart',), 'verbose_name': 'cart_item', 'verbose_name_plural': 'cart_items'},
        ),
    ]
