# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20160530_0550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('cart',), 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
    ]
