# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_pin',
            field=models.TextField(default=b'3cf76'),
        ),
    ]
