# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20160613_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_pin',
            field=models.TextField(default=b'd1729'),
        ),
    ]
