# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20160617_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercheckout',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usercheckout',
            name='sum_product',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
