# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20160613_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_sales_date',
            new_name='sales_date',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_from_account',
            new_name='from_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='sales_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_data',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_pin',
        ),
        migrations.AddField(
            model_name='account',
            name='data',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='pin',
            field=models.TextField(default=b'8d17a'),
        ),
    ]
