# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_usercheckout_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercheckout',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
