# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20160615_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pin',
            field=models.TextField(default=b'ead76'),
        ),
    ]
