# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0005_auto_20160619_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercheckout',
            name='user',
        ),
        migrations.AddField(
            model_name='usercheckout',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
