# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20160615_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pin',
            field=models.TextField(default=b'b3c49'),
        ),
    ]
